// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/andibalo/flip-test/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTransactionService creates a new instance of MockTransactionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionService {
	mock := &MockTransactionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransactionService is an autogenerated mock type for the TransactionService type
type MockTransactionService struct {
	mock.Mock
}

type MockTransactionService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionService) EXPECT() *MockTransactionService_Expecter {
	return &MockTransactionService_Expecter{mock: &_m.Mock}
}

// GetTotalBalance provides a mock function for the type MockTransactionService
func (_mock *MockTransactionService) GetTotalBalance(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetTotalBalance")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionService_GetTotalBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTotalBalance'
type MockTransactionService_GetTotalBalance_Call struct {
	*mock.Call
}

// GetTotalBalance is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTransactionService_Expecter) GetTotalBalance(ctx interface{}) *MockTransactionService_GetTotalBalance_Call {
	return &MockTransactionService_GetTotalBalance_Call{Call: _e.mock.On("GetTotalBalance", ctx)}
}

func (_c *MockTransactionService_GetTotalBalance_Call) Run(run func(ctx context.Context)) *MockTransactionService_GetTotalBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTransactionService_GetTotalBalance_Call) Return(n int64, err error) *MockTransactionService_GetTotalBalance_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockTransactionService_GetTotalBalance_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *MockTransactionService_GetTotalBalance_Call {
	_c.Call.Return(run)
	return _c
}

// GetUnsuccessfulTransactions provides a mock function for the type MockTransactionService
func (_mock *MockTransactionService) GetUnsuccessfulTransactions(ctx context.Context, req entity.GetIssuesFilter) (*entity.IssuesResponse, int64, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetUnsuccessfulTransactions")
	}

	var r0 *entity.IssuesResponse
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.GetIssuesFilter) (*entity.IssuesResponse, int64, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.GetIssuesFilter) *entity.IssuesResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.IssuesResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.GetIssuesFilter) int64); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, entity.GetIssuesFilter) error); ok {
		r2 = returnFunc(ctx, req)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockTransactionService_GetUnsuccessfulTransactions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUnsuccessfulTransactions'
type MockTransactionService_GetUnsuccessfulTransactions_Call struct {
	*mock.Call
}

// GetUnsuccessfulTransactions is a helper method to define mock.On call
//   - ctx context.Context
//   - req entity.GetIssuesFilter
func (_e *MockTransactionService_Expecter) GetUnsuccessfulTransactions(ctx interface{}, req interface{}) *MockTransactionService_GetUnsuccessfulTransactions_Call {
	return &MockTransactionService_GetUnsuccessfulTransactions_Call{Call: _e.mock.On("GetUnsuccessfulTransactions", ctx, req)}
}

func (_c *MockTransactionService_GetUnsuccessfulTransactions_Call) Run(run func(ctx context.Context, req entity.GetIssuesFilter)) *MockTransactionService_GetUnsuccessfulTransactions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.GetIssuesFilter
		if args[1] != nil {
			arg1 = args[1].(entity.GetIssuesFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionService_GetUnsuccessfulTransactions_Call) Return(issuesResponse *entity.IssuesResponse, n int64, err error) *MockTransactionService_GetUnsuccessfulTransactions_Call {
	_c.Call.Return(issuesResponse, n, err)
	return _c
}

func (_c *MockTransactionService_GetUnsuccessfulTransactions_Call) RunAndReturn(run func(ctx context.Context, req entity.GetIssuesFilter) (*entity.IssuesResponse, int64, error)) *MockTransactionService_GetUnsuccessfulTransactions_Call {
	_c.Call.Return(run)
	return _c
}

// UploadCSVFile provides a mock function for the type MockTransactionService
func (_mock *MockTransactionService) UploadCSVFile(ctx context.Context, fileContent []byte) (int, error) {
	ret := _mock.Called(ctx, fileContent)

	if len(ret) == 0 {
		panic("no return value specified for UploadCSVFile")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) (int, error)); ok {
		return returnFunc(ctx, fileContent)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) int); ok {
		r0 = returnFunc(ctx, fileContent)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = returnFunc(ctx, fileContent)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionService_UploadCSVFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadCSVFile'
type MockTransactionService_UploadCSVFile_Call struct {
	*mock.Call
}

// UploadCSVFile is a helper method to define mock.On call
//   - ctx context.Context
//   - fileContent []byte
func (_e *MockTransactionService_Expecter) UploadCSVFile(ctx interface{}, fileContent interface{}) *MockTransactionService_UploadCSVFile_Call {
	return &MockTransactionService_UploadCSVFile_Call{Call: _e.mock.On("UploadCSVFile", ctx, fileContent)}
}

func (_c *MockTransactionService_UploadCSVFile_Call) Run(run func(ctx context.Context, fileContent []byte)) *MockTransactionService_UploadCSVFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionService_UploadCSVFile_Call) Return(n int, err error) *MockTransactionService_UploadCSVFile_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockTransactionService_UploadCSVFile_Call) RunAndReturn(run func(ctx context.Context, fileContent []byte) (int, error)) *MockTransactionService_UploadCSVFile_Call {
	_c.Call.Return(run)
	return _c
}
