// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/andibalo/flip-test/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTransactionRepository creates a new instance of MockTransactionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionRepository {
	mock := &MockTransactionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransactionRepository is an autogenerated mock type for the TransactionRepository type
type MockTransactionRepository struct {
	mock.Mock
}

type MockTransactionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionRepository) EXPECT() *MockTransactionRepository_Expecter {
	return &MockTransactionRepository_Expecter{mock: &_m.Mock}
}

// Clear provides a mock function for the type MockTransactionRepository
func (_mock *MockTransactionRepository) Clear() {
	_mock.Called()
	return
}

// MockTransactionRepository_Clear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clear'
type MockTransactionRepository_Clear_Call struct {
	*mock.Call
}

// Clear is a helper method to define mock.On call
func (_e *MockTransactionRepository_Expecter) Clear() *MockTransactionRepository_Clear_Call {
	return &MockTransactionRepository_Clear_Call{Call: _e.mock.On("Clear")}
}

func (_c *MockTransactionRepository_Clear_Call) Run(run func()) *MockTransactionRepository_Clear_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTransactionRepository_Clear_Call) Return() *MockTransactionRepository_Clear_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTransactionRepository_Clear_Call) RunAndReturn(run func()) *MockTransactionRepository_Clear_Call {
	_c.Run(run)
	return _c
}

// GetAll provides a mock function for the type MockTransactionRepository
func (_mock *MockTransactionRepository) GetAll() ([]*model.Transaction, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*model.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]*model.Transaction, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []*model.Transaction); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockTransactionRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *MockTransactionRepository_Expecter) GetAll() *MockTransactionRepository_GetAll_Call {
	return &MockTransactionRepository_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *MockTransactionRepository_GetAll_Call) Run(run func()) *MockTransactionRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTransactionRepository_GetAll_Call) Return(transactions []*model.Transaction, err error) *MockTransactionRepository_GetAll_Call {
	_c.Call.Return(transactions, err)
	return _c
}

func (_c *MockTransactionRepository_GetAll_Call) RunAndReturn(run func() ([]*model.Transaction, error)) *MockTransactionRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetUnsuccessfulTransactions provides a mock function for the type MockTransactionRepository
func (_mock *MockTransactionRepository) GetUnsuccessfulTransactions(page int, pageSize int) ([]*model.Transaction, int64, error) {
	ret := _mock.Called(page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for GetUnsuccessfulTransactions")
	}

	var r0 []*model.Transaction
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(int, int) ([]*model.Transaction, int64, error)); ok {
		return returnFunc(page, pageSize)
	}
	if returnFunc, ok := ret.Get(0).(func(int, int) []*model.Transaction); ok {
		r0 = returnFunc(page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int, int) int64); ok {
		r1 = returnFunc(page, pageSize)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(int, int) error); ok {
		r2 = returnFunc(page, pageSize)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockTransactionRepository_GetUnsuccessfulTransactions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUnsuccessfulTransactions'
type MockTransactionRepository_GetUnsuccessfulTransactions_Call struct {
	*mock.Call
}

// GetUnsuccessfulTransactions is a helper method to define mock.On call
//   - page int
//   - pageSize int
func (_e *MockTransactionRepository_Expecter) GetUnsuccessfulTransactions(page interface{}, pageSize interface{}) *MockTransactionRepository_GetUnsuccessfulTransactions_Call {
	return &MockTransactionRepository_GetUnsuccessfulTransactions_Call{Call: _e.mock.On("GetUnsuccessfulTransactions", page, pageSize)}
}

func (_c *MockTransactionRepository_GetUnsuccessfulTransactions_Call) Run(run func(page int, pageSize int)) *MockTransactionRepository_GetUnsuccessfulTransactions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionRepository_GetUnsuccessfulTransactions_Call) Return(transactions []*model.Transaction, n int64, err error) *MockTransactionRepository_GetUnsuccessfulTransactions_Call {
	_c.Call.Return(transactions, n, err)
	return _c
}

func (_c *MockTransactionRepository_GetUnsuccessfulTransactions_Call) RunAndReturn(run func(page int, pageSize int) ([]*model.Transaction, int64, error)) *MockTransactionRepository_GetUnsuccessfulTransactions_Call {
	_c.Call.Return(run)
	return _c
}

// SaveBulk provides a mock function for the type MockTransactionRepository
func (_mock *MockTransactionRepository) SaveBulk(transactions []*model.Transaction) error {
	ret := _mock.Called(transactions)

	if len(ret) == 0 {
		panic("no return value specified for SaveBulk")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]*model.Transaction) error); ok {
		r0 = returnFunc(transactions)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactionRepository_SaveBulk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveBulk'
type MockTransactionRepository_SaveBulk_Call struct {
	*mock.Call
}

// SaveBulk is a helper method to define mock.On call
//   - transactions []*model.Transaction
func (_e *MockTransactionRepository_Expecter) SaveBulk(transactions interface{}) *MockTransactionRepository_SaveBulk_Call {
	return &MockTransactionRepository_SaveBulk_Call{Call: _e.mock.On("SaveBulk", transactions)}
}

func (_c *MockTransactionRepository_SaveBulk_Call) Run(run func(transactions []*model.Transaction)) *MockTransactionRepository_SaveBulk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []*model.Transaction
		if args[0] != nil {
			arg0 = args[0].([]*model.Transaction)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTransactionRepository_SaveBulk_Call) Return(err error) *MockTransactionRepository_SaveBulk_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactionRepository_SaveBulk_Call) RunAndReturn(run func(transactions []*model.Transaction) error) *MockTransactionRepository_SaveBulk_Call {
	_c.Call.Return(run)
	return _c
}
